import { messageBus } from "../../services/message-bus.js";
import { AgentRequest, AgentResponse } from "../../models/orchestrator.types.js";
import { ReporterResult } from "../../models/reporter.types.js";
import { TriageResult } from "../../models/triage.types.js";
import { SecurityResult } from "../../models/security.types.js";
import { DependencyResult } from "../../models/dependency.types.js";
import { geminiService } from "../../services/gemini.service.js";

/**
 * Reporter Agent
 * Synthesizes all previous agent outputs into a unified, developer-friendly Markdown report.
 */
export class ReporterAgent {
  constructor() {
    this.startListening();
  }

  private startListening() {
    messageBus.subscribeToRequest("reporter", async (req: AgentRequest) => {
      try {
        console.info(`[ReporterAgent] Generating report for session ${req.sessionId}`);
        const result = await this.run(req);
        
        const response: AgentResponse<ReporterResult> = {
          sessionId: req.sessionId,
          agentId: "reporter",
          status: "SUCCESS",
          data: result,
        };
        messageBus.publishResponse("reporter", response);
      } catch (error: any) {
        console.error(`[ReporterAgent] Failed to generate report for session ${req.sessionId}:`, error);
        messageBus.publishResponse("reporter", {
          sessionId: req.sessionId,
          agentId: "reporter",
          status: "FAILED",
          error: error.message,
        });
      }
    });
  }

  public async run(req: AgentRequest): Promise<ReporterResult> {
    const triage: TriageResult = req.payload?.triage || {};
    const security: SecurityResult = req.payload?.security || { findings: [], criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 0, riskScore: 0 };
    const dependency: DependencyResult = req.payload?.dependency || { vulnerabilities: [], riskScore: 0 };
    
    // Calculate global risk (average of triage, security, dependency risks)
    const overallRiskScore = Math.round(((triage.riskScore || 0) + (security.riskScore || 0) + (dependency.riskScore || 0)) / 3);

    const isBlocked = security.criticalCount > 0 || dependency.vulnerabilities.some(v => v.severity === "CRITICAL");
    
    let executiveSummary = isBlocked 
      ? "🚫 **MERGE BLOCKED**: Critical security vulnerabilities detected." 
      : "✅ **PASSED**: No critical issues detected. Review recommended.";

    try {
      const prompt = `You are a Lead Application Security Reviewer. Write a 2-3 sentence executive summary of these security and dependency findings. Emphasize whether it is safe to merge or if it must be blocked. Be concise, professional, and do not use markdown formatting like asterisks.`;
      const aiSummary = await geminiService.generateSummary({ security, dependency }, prompt);
      if (aiSummary && !aiSummary.includes('unavailable')) {
        executiveSummary = aiSummary.trim();
      }
    } catch (e) {
      console.error("[ReporterAgent] Failed to generate AI summary, falling back to static.");
    }

    const markdownBody = this.generateMarkdown(triage, security, dependency, overallRiskScore, executiveSummary);

    return {
      markdownBody,
      jsonSummary: {
        riskScore: overallRiskScore,
        blocked: isBlocked
      },
      overallRiskScore,
      executiveSummary,
      securitySummary: security.securitySummary || "Clean",
      dependencySummary: dependency.summary || "Clean"
    };
  }

  private generateMarkdown(
    triage: TriageResult, 
    security: SecurityResult, 
    dependency: DependencyResult,
    riskScore: number,
    execSummary: string
  ): string {
    let md = `# 🛡️ Mutagent Security Review\n\n`;
    md += `> ${execSummary}\n\n`;
    md += `**Overall Risk Score:** ${riskScore}/100\n\n`;

    if (security.findings.length > 0) {
      md += `## 🔒 Security Findings\n\n`;
      security.findings.forEach(f => {
        const icon = f.severity === "CRITICAL" ? "🚨" : f.severity === "HIGH" ? "🔴" : f.severity === "MEDIUM" ? "🟠" : "🟡";
        md += `### ${icon} ${f.title} (${f.severity})\n`;
        md += `- **File:** \`${f.file}\` (Line: ${f.line || 'unknown'})\n`;
        md += `- **Description:** ${f.description}\n`;
        if (f.evidence) md += `- **Evidence:** \`${f.evidence}\`\n`;
        if (f.suggestedFix) md += `- **Fix:** ${f.suggestedFix}\n`;
        md += `\n`;
      });
    } else {
      md += `## 🔒 Security Findings\n✅ No security vulnerabilities found in the code changes.\n\n`;
    }

    if (dependency.vulnerabilities && dependency.vulnerabilities.length > 0) {
      md += `## 📦 Dependency Vulnerabilities\n\n`;
      dependency.vulnerabilities.forEach(v => {
        md += `- **${v.packageName}** (${v.severity}): ${v.description}. *Fix: ${v.recommendation}*\n`;
      });
      md += `\n`;
    }

    md += `---\n*Generated by [Mutagent](https://mutagent.dev)*`;
    return md;
  }
}

export const reporterAgent = new ReporterAgent();
