import type { SecurityReport } from "../../types/security";

export const reports: SecurityReport[] = [
  {
    id: "RPT-2026-0814",
    repository: "fintech-core",
    pullRequest: "#482",
    title: "Harden token exchange flow",
    author: "Aarav Mehta",
    date: "2026-08-07",
    status: "blocked",
    severity: "critical",
    score: 62,
    executiveSummary:
      "OAuth token exchange improvements are directionally correct, but upstream error reflection can expose tenant metadata and should block merge until normalized.",
    securityFindings: ["Provider diagnostic body reflected in API response", "Replay telemetry missing for refresh token rotation"],
    dependencyFindings: ["jose transitive version requires advisory review", "openid-client pin matches policy baseline"],
    qualityFindings: ["Retry branch requires typed upstream error boundary", "Expired verifier regression test missing"],
    attackSimulations: ["OAuth provider error reflection reproduced tenant hints across retry branch", "Malformed verifier replay rejected after second rotation"],
    recommendations: ["Normalize provider errors", "Emit replay attempts to audit-log", "Add verifier expiry regression tests"],
  },
  {
    id: "RPT-2026-0809",
    repository: "identity-gateway",
    pullRequest: "#477",
    title: "Upgrade auth middleware",
    author: "Nisha Rao",
    date: "2026-08-07",
    status: "blocked",
    severity: "high",
    score: 71,
    executiveSummary:
      "Issuer validation improved, but degraded cache behavior preserves stale tenant grants and should fail closed for privileged paths.",
    securityFindings: ["Stale tenant grant accepted during policy cache miss"],
    dependencyFindings: ["No vulnerable runtime dependencies introduced"],
    qualityFindings: ["Degraded-mode cache state needs explicit domain type"],
    attackSimulations: ["Revoked reviewer token retained access for 90 seconds during cache degradation"],
    recommendations: ["Fail closed on cache miss", "Reduce degraded cache TTL", "Add revocation simulation coverage"],
  },
  {
    id: "RPT-2026-0798",
    repository: "payments-api",
    pullRequest: "#463",
    title: "Payment webhook reconciliation",
    author: "Kabir Singh",
    date: "2026-08-06",
    status: "approved",
    severity: "medium",
    score: 86,
    executiveSummary:
      "Webhook reconciliation is release-ready with strong idempotency controls and a non-blocking observability recommendation.",
    securityFindings: ["Replay rejection counter not surfaced in dashboard telemetry"],
    dependencyFindings: ["Stripe SDK version aligns with policy baseline"],
    qualityFindings: ["Ledger transaction boundaries are clear and tested"],
    attackSimulations: ["Replay storm of 10,000 duplicate webhooks produced no balance drift"],
    recommendations: ["Add webhook replay metric", "Create runbook alert threshold for duplicate signatures"],
  },
  {
    id: "RPT-2026-0771",
    repository: "merchant-portal",
    pullRequest: "#455",
    title: "Admin invite redesign",
    author: "Isha Kapoor",
    date: "2026-08-05",
    status: "open",
    severity: "low",
    score: 92,
    executiveSummary:
      "Admin invite changes preserve scoped tokens and improve audit trail clarity. Final accessibility review remains pending.",
    securityFindings: ["No blocking security findings"],
    dependencyFindings: ["No dependency changes"],
    qualityFindings: ["Server action boundaries are clear", "Form validation is covered"],
    attackSimulations: ["Invite token brute-force simulation failed against configured rate limits"],
    recommendations: ["Complete accessibility review", "Ship with audit copy updates"],
  },
];
